### ISSUE TITLE
opcodes

### ISSUE THREAD

**Issue by Bluebottles** [exectails/MabiPale2#17]
hi sorry to bother you exec, i don't really understand how to use mabipale. i'm using the latest release of this and morrighan, i've read on the nocodenolife forum that connecting to morrighan will only return the login packets now? the problem is i'm trying to find the latest opcodes to use with mabicommerce, which i was told to figure out by using mabipale, so i don't really know how i can do that if all i can get from morrighan now is the login packets

**Comment by exectails** [comment]
Hi. I'm not sure why you think that Morrighan would only log login packets. Both Morrighan's readme and the thread on NoCodeNoLife state the following:
>Right now Morrighan only supports the Login and Channel servers, you won't get any messenger packets

That means you can't log messenger packets (like private chats or guild chat), but everything else is fine. You should be able to run Morrighan and Pale while talking to the commerce NPCs and then glean the current opcodes from the packets that were being sent by the server. Maybe we can shorten this a little though.
```text
CommerceProductListRequest = 0xAADA
CommerceInfoUpdate = 0xAAE1
CommerceInfoRequest = 0xAAE6
```
These should be the current opcodes for MabiCommerce.

Maybe a _ certain someone_, @Xcelled, should've added a packet identification feature to their tool =P

**Comment by exectails** [comment]
I shouldn't matter whether you're deleting the files or not. If you don't get the prompt to click start in the launcher, the parameters you're passing to Morrighan are presumably incorrect. Could you tell me how you're launching it and which parameters you're using?

**Comment by Bluebottles** [comment]
i created a shortcut to morrighan.exe (the latest release, 1.6.2) within my mabi folder, and changed the target of the shortcut to

`Morrighan.exe code:1622 verstr:248 ver:248 locale:USA env:Regular setting:file://data/features.xml logip:35.162.171.43 logport:11000 chatip:54.214.176.167 chatport:8002 nxlauncher`

after hitting apply, the final target looks like this

`D:\mabinogi\appdata\Morrighan.exe code:1622 verstr:248 ver:248 locale:USA env:Regular setting:file://data/features.xml logip:35.162.171.43 logport:11000 chatip:54.214.176.167 chatport:8002 nxlauncher`

first time i run the shortcut, the little window with instructions pops up and it's fine. after that, the game launches right away and i can't log in.

**Comment by Bluebottles** [comment]
i'm not asked to enter my details the first time, so i am logged in automatically from the nexon launcher i guess. mabicommerce doesn't work in that instance and neither does mabipale, except for 2 packets, ClientIdent and LoginIdent. no others show up

**Comment by exectails** [comment]
Yea, the launcher essentially passes the login information to the client. The issue is presumably LoginRedirect, which diverts the connection to another login server. NA didn't use this in the past. However, Morrighan is _supposed_ to be able to handle that. I'll have to look into what's happening there.

**Comment by exectails** [comment]
Found the issue and fixed it. With the latest version of Morrighan (1.6.3) you should now be able to use Pale and MabiCommerce again.
https://github.com/exectails/Morrighan/releases

**Comment by Bluebottles** [comment]
both mabicommerce and mabipale are working great now, thanks so much for helping!
