### ISSUE TITLE
Failure to load plugins

### ISSUE THREAD

**Issue by YaibaToKen** [exectails/MabiPale2#7]
So.. Whenever I start up the program, I get these errors telling me it couldn't load plugins. This occurs for all 4 of the base plugins :/ 

Here are the printscreens of them errors:

![hexpacketparser](https://cloud.githubusercontent.com/assets/9133736/12766847/b3c7b30e-c9fd-11e5-864f-41d5e42e12ee.png)
![packetanalyzer](https://cloud.githubusercontent.com/assets/9133736/12766848/b3d608aa-c9fd-11e5-8d75-7aa697efbf65.png)
![dungen](https://cloud.githubusercontent.com/assets/9133736/12766849/b3d70232-c9fd-11e5-9986-4136a7f5734c.png)
![entitylogger](https://cloud.githubusercontent.com/assets/9133736/12766850/b3d77ea6-c9fd-11e5-95d5-5982315ba8e9.png)

**Comment by exectails** [comment]
Could you try to "unblock" the plugin DLLs, as described [here](http://stackoverflow.com/questions/21753979/visual-studio-could-not-load-file-or-assembly-operation-is-not-supported-erro)? Apparently this is a security mechanism of Windows 8+, which prevents applications from using "unknown" DLLs.

**Comment by YaibaToKen** [comment]
Thanks for the really quick reply :) and yes, that worked! Thank you so much for all the great work. On another note, is there any know issue with the confirmation emails for the forums? I've tried several times yet no confirmation email on my inbox or spam folder :/

**Comment by exectails** [comment]
Yea =/ For some reason the mails never seem to arrive if you're using a Microsoft mail. I've just approved your account manually.

**Comment by YaibaToKen** [comment]
Thank you, you might want to note that down somewhere in the forums then :)
